development:
  :host: "localhost:8088"
  :smtp:
    :domain: "localhost:8088"
    :host: "localhost:8088"
    :port: 587
    :username: "setlister"
    :password: "setlister"

production:
  :host: "setlister.lifepointoakdale.org"
  :smtp:
    :domain: "setlister.lifepointoakdale.org"
    :host: <%= ENV['MAILGUN_SMTP_SERVER'] %>
    :port: <%= ENV['MAILGUN_SMTP_PORT'] %>
    :username: <%= ENV['MAILGUN_SMTP_LOGIN'] %>
    :password: <%= ENV['MAILGUN_SMTP_PASSWORD'] %>
